services:
  - type: web
    name: fakenewsdetector
    env: python
    region: oregon
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
    pythonVersion: "3.14"
    plan: free

